"""`yt-collector run`: new videos -> transcript -> LLM note -> INDEX.md."""
from __future__ import annotations

import json
import re
from datetime import datetime, timedelta, timezone
from pathlib import Path

from . import llm, log, oauth, prompts, youtube
from .config import Config, check_llm

MAX_LLM_FAILURES = 3
INDEX_HEADER = ["# Knowledge feed", "",
                "Generated by yt-collector. One line per video, newest first.", ""]


class StateError(RuntimeError):
    """state.json exists but cannot be read; refusing to reprocess the whole history."""


def load_state(path: Path) -> dict:
    if not path.exists():
        return {"seen": [], "resolved": {}, "failures": {}, "last_run": None}
    try:
        state = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        raise StateError(f"{path} is not valid JSON ({e}); fix or delete it") from e
    state.setdefault("failures", {})
    return state


def save_state(path: Path, state: dict) -> None:
    tmp = path.with_suffix(".tmp")
    tmp.write_text(json.dumps(state, indent=2, ensure_ascii=False), encoding="utf-8")
    tmp.replace(path)


def matches_keywords(video: dict, keywords: list[str]) -> bool:
    """Whole-word, case-insensitive match on title + description.

    'ai' matches 'AI' but not 'rain'."""
    if not keywords:
        return True
    hay = f"{video['title']} {video['desc']}".lower()
    return any(re.search(rf"(?<!\w){re.escape(k.lower())}(?!\w)", hay) for k in keywords)


def slugify(s: str, n: int = 50) -> str:
    s = re.sub(r"[^\w\s-]", "", s).strip().lower()
    s = re.sub(r"[\s_-]+", "-", s)
    return s[:n].strip("-") or "video"


def note_path(out: Path, video: dict) -> Path:
    pub = video["published"][:10] or "undated"
    folder = out / (pub[:7] if pub != "undated" else pub)
    name = f"{pub}_{slugify(video['author'], 20)}_{slugify(video['title'])}_{video['id']}.md"
    return folder / name


def write_note(out: Path, video: dict, body: str, now: datetime) -> Path:
    path = note_path(out, video)
    path.parent.mkdir(parents=True, exist_ok=True)
    pub = video["published"][:10] or "undated"
    front = (
        "---\n"
        f"title: {json.dumps(video['title'], ensure_ascii=False)}\n"
        f"channel: {json.dumps(video['author'], ensure_ascii=False)}\n"
        f"url: {video['url']}\n"
        f"video_id: {video['id']}\n"
        f"published: {video['published']}\n"
        f"collected: {now.isoformat()}\n"
        "source: yt-collector\n"
        "---\n\n"
        f"# {video['title']}\n\n"
        f"> {video['author']} · [{video['url']}]({video['url']}) · {pub}\n\n"
    )
    path.write_text(front + body + "\n", encoding="utf-8")
    return path


def update_index(out: Path, notes: list[tuple[dict, Path]]) -> None:
    idx = out / "INDEX.md"
    lines = idx.read_text(encoding="utf-8").splitlines() if idx.exists() else []
    if lines[:len(INDEX_HEADER)] != INDEX_HEADER:
        lines = INDEX_HEADER + lines
    body = lines[len(INDEX_HEADER):]
    new = []
    for v, path in notes:
        rel = path.relative_to(out).as_posix()
        if any(f"({rel})" in line for line in body):
            continue
        new.append(f"- `{v['published'][:10] or '?'}` **{v['author']}** — "
                   f"[{v['title']}]({rel}) · [video]({v['url']})")
    idx.write_text("\n".join(INDEX_HEADER + new + body) + "\n", encoding="utf-8")


def gather_channels(cfg: Config, state: dict) -> tuple[list[str], set[str]]:
    entries = youtube.read_list(cfg.path("YTC_CHANNELS"))
    subs = oauth.subscription_channel_ids()
    if subs:
        added = [c for c in subs if c not in entries]
        entries += added
        log(f"subscriptions: {len(subs)} (+{len(added)} not in channels file)")
    blocked = set()
    for entry in youtube.read_list(cfg.path("YTC_BLOCKLIST")):
        cid = youtube.resolve_channel(entry, state["resolved"])
        if cid:
            blocked.add(cid)
    return entries, blocked


def run(cfg: Config, now: datetime | None = None) -> int:
    """Returns 0 on success, 1 if any LLM call failed (videos are retried next run)."""
    now = now or datetime.now(timezone.utc)
    check_llm(cfg)
    out = cfg.path("YTC_OUT")
    state_path = cfg.path("YTC_STATE")
    state = load_state(state_path)
    seen = set(state["seen"])
    failures: dict[str, int] = state["failures"]
    keywords = cfg.list("YTC_KEYWORDS")

    entries, blocked = gather_channels(cfg, state)
    if not entries:
        log(f"no channels: add some to {cfg.path('YTC_CHANNELS')}")
        return 1

    first_run = state.get("last_run") is None
    cutoff = now - timedelta(hours=cfg.float("YTC_LOOKBACK_HOURS"))
    candidates = []
    for entry in entries:
        cid = youtube.resolve_channel(entry, state["resolved"])
        if not cid or cid in blocked:
            continue
        for v in youtube.channel_videos(cid):
            if v["id"] in seen:
                continue
            try:
                v["_pub"] = datetime.fromisoformat(v["published"].replace("Z", "+00:00"))
            except ValueError:
                v["_pub"] = now
            if (first_run and v["_pub"] < cutoff) or not matches_keywords(v, keywords):
                seen.add(v["id"])
                continue
            candidates.append(v)

    candidates.sort(key=lambda v: v["_pub"])
    cap = cfg.int("YTC_MAX_PER_RUN")
    if len(candidates) > cap:
        log(f"{len(candidates)} candidates; processing the {cap} most recent, "
            "the rest on later runs")
        candidates = candidates[-cap:]
    log(f"{len(candidates)} new video(s)" + (" (first run)" if first_run else ""))

    system = prompts.note_system(cfg["YTC_SUMMARY_LANG"], cfg["YTC_TOPIC"])
    written: list[tuple[dict, Path]] = []
    llm_errors = 0
    for v in candidates:
        log(f"> {v['author']}: {v['title']}")
        text = youtube.transcript(cfg, v["url"])
        if len(text) < 200:
            log("  no usable transcript, skipping")
            seen.add(v["id"])
            continue
        user = (f"VIDEO: {v['title']}\nCHANNEL: {v['author']}\nURL: {v['url']}\n"
                f"PUBLISHED: {v['published']}\n\nTRANSCRIPT:\n{text}\n")
        try:
            body = llm.complete(cfg, system, user)
        except llm.LLMError as e:
            llm_errors += 1
            failures[v["id"]] = failures.get(v["id"], 0) + 1
            log(f"  LLM error ({failures[v['id']]}/{MAX_LLM_FAILURES}): {e}")
            if failures[v["id"]] >= MAX_LLM_FAILURES:
                seen.add(v["id"])
                failures.pop(v["id"])
            continue
        failures.pop(v["id"], None)
        seen.add(v["id"])
        if body.strip("` \n").startswith(prompts.SKIP_MARKER):
            log("  off-topic, skipping")
            continue
        path = write_note(out, v, body, now)
        log(f"  wrote {path.relative_to(out)}")
        written.append((v, path))

    if written:
        update_index(out, written)
    state["seen"] = sorted(seen)
    state["last_run"] = now.isoformat()
    save_state(state_path, state)
    log(f"done: {len(written)} note(s), {llm_errors} LLM error(s), {len(seen)} ids seen")
    return 1 if llm_errors else 0
